DROP TABLE IF EXISTS schools.school_membership_2015;
CREATE TABLE schools.school_membership_2015(
"survyear" VARCHAR(36)
, "fipst" SMALLINT
, "stabr" VARCHAR(8)
, "statename" VARCHAR(192)
, "seaname" VARCHAR(472)
, "leaid" INT
, "st_leaid" VARCHAR(112)
, "lea_name" VARCHAR(480)
, "schid" INT
, "st_schid" VARCHAR(160)
, "ncessch" BIGINT
, "sch_name" VARCHAR(480)
, "pk" SMALLINT
, "kg" SMALLINT
, "g01" SMALLINT
, "g02" SMALLINT
, "g03" SMALLINT
, "g04" SMALLINT
, "g05" SMALLINT
, "g06" SMALLINT
, "g07" SMALLINT
, "g08" SMALLINT
, "g09" SMALLINT
, "g10" SMALLINT
, "g11" SMALLINT
, "g12" SMALLINT
, "g13" SMALLINT
, "ug" SMALLINT
, "ae" SMALLINT
, "total" INT
, "member" INT
, "ampkm" SMALLINT
, "ampkf" SMALLINT
, "aspkm" SMALLINT
, "aspkf" SMALLINT
, "hipkm" SMALLINT
, "hipkf" SMALLINT
, "blpkm" SMALLINT
, "blpkf" SMALLINT
, "whpkm" SMALLINT
, "whpkf" SMALLINT
, "hppkm" SMALLINT
, "hppkf" SMALLINT
, "trpkm" SMALLINT
, "trpkf" SMALLINT
, "amkgm" SMALLINT
, "amkgf" SMALLINT
, "askgm" SMALLINT
, "askgf" SMALLINT
, "hikgm" SMALLINT
, "hikgf" SMALLINT
, "blkgm" SMALLINT
, "blkgf" SMALLINT
, "whkgm" SMALLINT
, "whkgf" SMALLINT
, "hpkgm" SMALLINT
, "hpkgf" SMALLINT
, "trkgm" SMALLINT
, "trkgf" SMALLINT
, "am01m" SMALLINT
, "am01f" SMALLINT
, "as01m" SMALLINT
, "as01f" SMALLINT
, "hi01m" SMALLINT
, "hi01f" SMALLINT
, "bl01m" SMALLINT
, "bl01f" SMALLINT
, "wh01m" SMALLINT
, "wh01f" SMALLINT
, "hp01m" SMALLINT
, "hp01f" SMALLINT
, "tr01m" SMALLINT
, "tr01f" SMALLINT
, "am02m" SMALLINT
, "am02f" SMALLINT
, "as02m" SMALLINT
, "as02f" SMALLINT
, "hi02m" SMALLINT
, "hi02f" SMALLINT
, "bl02m" SMALLINT
, "bl02f" SMALLINT
, "wh02m" SMALLINT
, "wh02f" SMALLINT
, "hp02m" SMALLINT
, "hp02f" SMALLINT
, "tr02m" SMALLINT
, "tr02f" SMALLINT
, "am03m" SMALLINT
, "am03f" SMALLINT
, "as03m" SMALLINT
, "as03f" SMALLINT
, "hi03m" SMALLINT
, "hi03f" SMALLINT
, "bl03m" SMALLINT
, "bl03f" SMALLINT
, "wh03m" SMALLINT
, "wh03f" SMALLINT
, "hp03m" SMALLINT
, "hp03f" SMALLINT
, "tr03m" SMALLINT
, "tr03f" SMALLINT
, "am04m" SMALLINT
, "am04f" SMALLINT
, "as04m" SMALLINT
, "as04f" SMALLINT
, "hi04m" SMALLINT
, "hi04f" SMALLINT
, "bl04m" SMALLINT
, "bl04f" SMALLINT
, "wh04m" SMALLINT
, "wh04f" SMALLINT
, "hp04m" SMALLINT
, "hp04f" SMALLINT
, "tr04m" SMALLINT
, "tr04f" SMALLINT
, "am05m" SMALLINT
, "am05f" SMALLINT
, "as05m" SMALLINT
, "as05f" SMALLINT
, "hi05m" SMALLINT
, "hi05f" SMALLINT
, "bl05m" SMALLINT
, "bl05f" SMALLINT
, "wh05m" SMALLINT
, "wh05f" SMALLINT
, "hp05m" SMALLINT
, "hp05f" SMALLINT
, "tr05m" SMALLINT
, "tr05f" SMALLINT
, "am06m" SMALLINT
, "am06f" SMALLINT
, "as06m" SMALLINT
, "as06f" SMALLINT
, "hi06m" SMALLINT
, "hi06f" SMALLINT
, "bl06m" SMALLINT
, "bl06f" SMALLINT
, "wh06m" SMALLINT
, "wh06f" SMALLINT
, "hp06m" SMALLINT
, "hp06f" SMALLINT
, "tr06m" SMALLINT
, "tr06f" SMALLINT
, "am07m" SMALLINT
, "am07f" SMALLINT
, "as07m" SMALLINT
, "as07f" SMALLINT
, "hi07m" SMALLINT
, "hi07f" SMALLINT
, "bl07m" SMALLINT
, "bl07f" SMALLINT
, "wh07m" SMALLINT
, "wh07f" SMALLINT
, "hp07m" SMALLINT
, "hp07f" SMALLINT
, "tr07m" SMALLINT
, "tr07f" SMALLINT
, "am08m" SMALLINT
, "am08f" SMALLINT
, "as08m" SMALLINT
, "as08f" SMALLINT
, "hi08m" SMALLINT
, "hi08f" SMALLINT
, "bl08m" SMALLINT
, "bl08f" SMALLINT
, "wh08m" SMALLINT
, "wh08f" SMALLINT
, "hp08m" SMALLINT
, "hp08f" SMALLINT
, "tr08m" SMALLINT
, "tr08f" SMALLINT
, "am09m" SMALLINT
, "am09f" SMALLINT
, "as09m" SMALLINT
, "as09f" SMALLINT
, "hi09m" SMALLINT
, "hi09f" SMALLINT
, "bl09m" SMALLINT
, "bl09f" SMALLINT
, "wh09m" SMALLINT
, "wh09f" SMALLINT
, "hp09m" SMALLINT
, "hp09f" SMALLINT
, "tr09m" SMALLINT
, "tr09f" SMALLINT
, "am10m" SMALLINT
, "am10f" SMALLINT
, "as10m" SMALLINT
, "as10f" SMALLINT
, "hi10m" SMALLINT
, "hi10f" SMALLINT
, "bl10m" SMALLINT
, "bl10f" SMALLINT
, "wh10m" SMALLINT
, "wh10f" SMALLINT
, "hp10m" SMALLINT
, "hp10f" SMALLINT
, "tr10m" SMALLINT
, "tr10f" SMALLINT
, "am11m" SMALLINT
, "am11f" SMALLINT
, "as11m" SMALLINT
, "as11f" SMALLINT
, "hi11m" SMALLINT
, "hi11f" SMALLINT
, "bl11m" SMALLINT
, "bl11f" SMALLINT
, "wh11m" SMALLINT
, "wh11f" SMALLINT
, "hp11m" SMALLINT
, "hp11f" SMALLINT
, "tr11m" SMALLINT
, "tr11f" SMALLINT
, "am12m" SMALLINT
, "am12f" SMALLINT
, "as12m" SMALLINT
, "as12f" SMALLINT
, "hi12m" SMALLINT
, "hi12f" SMALLINT
, "bl12m" SMALLINT
, "bl12f" SMALLINT
, "wh12m" SMALLINT
, "wh12f" SMALLINT
, "hp12m" SMALLINT
, "hp12f" SMALLINT
, "tr12m" SMALLINT
, "tr12f" SMALLINT
, "am13m" SMALLINT
, "am13f" SMALLINT
, "as13m" SMALLINT
, "as13f" SMALLINT
, "hi13m" SMALLINT
, "hi13f" SMALLINT
, "bl13m" SMALLINT
, "bl13f" SMALLINT
, "wh13m" SMALLINT
, "wh13f" SMALLINT
, "hp13m" SMALLINT
, "hp13f" SMALLINT
, "tr13m" SMALLINT
, "tr13f" SMALLINT
, "amugm" SMALLINT
, "amugf" SMALLINT
, "asugm" SMALLINT
, "asugf" SMALLINT
, "hiugm" SMALLINT
, "hiugf" SMALLINT
, "blugm" SMALLINT
, "blugf" SMALLINT
, "whugm" SMALLINT
, "whugf" SMALLINT
, "hpugm" SMALLINT
, "hpugf" SMALLINT
, "trugm" SMALLINT
, "trugf" SMALLINT
, "amaem" SMALLINT
, "amaef" SMALLINT
, "asaem" SMALLINT
, "asaef" SMALLINT
, "hiaem" SMALLINT
, "hiaef" SMALLINT
, "blaem" SMALLINT
, "blaef" SMALLINT
, "whaem" SMALLINT
, "whaef" SMALLINT
, "hpaem" SMALLINT
, "hpaef" SMALLINT
, "traem" SMALLINT
, "traef" SMALLINT
, "am" SMALLINT
, "amalm" SMALLINT
, "amalf" SMALLINT
, "as" SMALLINT
, "asalm" SMALLINT
, "asalf" SMALLINT
, "hi" SMALLINT
, "hialm" SMALLINT
, "hialf" SMALLINT
, "bl" SMALLINT
, "blalm" SMALLINT
, "blalf" SMALLINT
, "wh" INT
, "whalm" SMALLINT
, "whalf" SMALLINT
, "hp" SMALLINT
, "hpalm" SMALLINT
, "hpalf" SMALLINT
, "tr" SMALLINT
, "tralm" SMALLINT
, "tralf" SMALLINT
, "ismempup" VARCHAR(112)
, "ispelm" VARCHAR(112)
, "ispfemale" VARCHAR(112)
, "ispwhite" VARCHAR(112)
);
