DROP TABLE IF EXISTS schools.school_directory_import_2015;
CREATE TABLE schools.school_directory_import_2015(
"survyear" VARCHAR(36)
, "fipst" SMALLINT
, "stabr" VARCHAR(8)
, "statename" VARCHAR(192)
, "seaname" VARCHAR(472)
, "leaid" INT
, "st_leaid" VARCHAR(112)
, "lea_name" VARCHAR(480)
, "schid" INT
, "st_schid" VARCHAR(160)
, "ncessch" BIGINT
, "sch_name" VARCHAR(480)
, "mstreet1" VARCHAR(240)
, "mstreet2" VARCHAR(240)
, "mstreet3" VARCHAR(184)
, "mcity" VARCHAR(208)
, "mstate" VARCHAR(8)
, "mzip" INT
, "mzip4" SMALLINT
, "phone" BIGINT
, "lstreet1" VARCHAR(240)
, "lstreet2" VARCHAR(240)
, "lstreet3" VARCHAR(224)
, "lcity" VARCHAR(208)
, "lstate" VARCHAR(8)
, "lzip" INT
, "lzip4" SMALLINT
, "union" SMALLINT
, "out_of_state_flag" VARCHAR(4)
, "sch_type_text" VARCHAR(224)
, "sch_type" SMALLINT
, "recon_status" VARCHAR(24)
, "gslo" VARCHAR(16)
, "gshi" VARCHAR(16)
, "level" VARCHAR(4)
, "virtual" VARCHAR(56)
, "bies" SMALLINT
, "sy_status_text" VARCHAR(112)
, "sy_status" SMALLINT
, "updated_status_text" VARCHAR(112)
, "updated_status" SMALLINT
, "effective_date" VARCHAR(72)
, "charter_text" VARCHAR(112)
, "pkoffered" VARCHAR(4)
, "kgoffered" VARCHAR(4)
, "g1offered" VARCHAR(4)
, "g2offered" VARCHAR(4)
, "g3offered" VARCHAR(4)
, "g4offered" VARCHAR(4)
, "g5offered" VARCHAR(4)
, "g6offered" VARCHAR(4)
, "g7offered" VARCHAR(4)
, "g8offered" VARCHAR(4)
, "g9offered" VARCHAR(4)
, "g10offered" VARCHAR(4)
, "g11offered" VARCHAR(4)
, "g12offered" VARCHAR(4)
, "g13offered" VARCHAR(4)
, "aeoffered" VARCHAR(4)
, "ugoffered" VARCHAR(4)
, "nogrades" VARCHAR(4)
, "chartauth1" VARCHAR(480)
, "chartauthn1" VARCHAR(112)
, "chartauth2" VARCHAR(56)
, "chartauthn2" VARCHAR(56)
, "igoffered" VARCHAR(4)
);
